let kb = MapQuestion(location: CLLocationCoordinate2D(latitude:   67.074411, longitude:-158.945477), regionSizeInMeters: 1000)
kb.addAnswer("Alaska", isCorrect: true)
kb.addAnswer("Sahara Desert", isCorrect: false)
kb.addAnswer("Arizona", isCorrect: false)
self.questions.append(kb)
	
let ba = MapQuestion(location: CLLocationCoordinate2D(latitude: 44.499527, longitude: 33.598420), regionSizeInMeters: 500)
ba.addAnswer("Turkey", isCorrect: false)
ba.addAnswer("Russia", isCorrect: true)
ba.addAnswer("Italy", isCorrect: false)
self.questions.append(ba)
	
let ca = MapQuestion(location: CLLocationCoordinate2D(latitude: 32.675831, longitude:-117.157526), regionSizeInMeters: 500)
ca.addAnswer("California", isCorrect: true)
ca.addAnswer("Germany", isCorrect: false)
ca.addAnswer("Italy", isCorrect: false)
self.questions.append(ca)
	
let ar = MapQuestion(location: CLLocationCoordinate2D(latitude: -33.867886, longitude:-63.984500), regionSizeInMeters: 1500)
ar.addAnswer("Tennessee", isCorrect: false)
ar.addAnswer("Argentina", isCorrect: true)
ar.addAnswer("New Mexico", isCorrect: false)
self.questions.append(ar)
	
let ch = MapQuestion(location: CLLocationCoordinate2D(latitude: 40.452107, longitude: 93.742118), regionSizeInMeters: 2500)
ch.addAnswer("Peru", isCorrect: false)
ch.addAnswer("China", isCorrect: true)
ch.addAnswer("Egypt", isCorrect: false)
self.questions.append(ch)
	
let nv = MapQuestion(location: CLLocationCoordinate2D(latitude: 37.563936, longitude: -116.851230), regionSizeInMeters: 500)
nv.addAnswer("Nevada", isCorrect: true)
nv.addAnswer("China", isCorrect: false)
nv.addAnswer("Egypt", isCorrect: false)
self.questions.append(nv)
	
let sa = MapQuestion(location: CLLocationCoordinate2D(latitude: 16.864841, longitude:  11.953808), regionSizeInMeters: 500)
sa.addAnswer("Sahara Desert", isCorrect: true)
sa.addAnswer("Nevada", isCorrect: false)
sa.addAnswer("Egypt", isCorrect: false)
self.questions.append(sa)
	
	
let bs = MapQuestion(location: CLLocationCoordinate2D(latitude: 26.357896, longitude: 127.783809), regionSizeInMeters: 200)
bs.addAnswer("Japan", isCorrect: true)
bs.addAnswer("New York", isCorrect: false)
bs.addAnswer("Tibet", isCorrect: false)
self.questions.append(bs)